version: '3.8'

services:
  inkcore:
    build: .
    container_name: inkcore
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  inkworker:
    build: .
    container_name: inkworker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: inkgrid-redis
    ports:
      - "6379:6379"
